### ISSUE TITLE
Wrong URL for rendered version of git-novice-es workshop

### ISSUE THREAD

**Issue by olemis** [swcarpentry/git-novice-es#67]
The [README of the English version of the workshop](https://github.com/swcarpentry/git-novice/blob/gh-pages/README.md) redirects to https://swcarpentry.github.io/git-novice/ whereas the [Spanish translation](https://github.com/swcarpentry/git-novice-es/blob/gh-pages/README.md) forwards readers onto https://github.com/Carpentries-ES/git-novice/tree/gh-pages/_episodes_es/

**Comment by raynamharris** [comment]
Good catch! This is because there was a time when the Spanish version lived in the carpenters-es repo. The correct link should be https://swcarpentry.github.io/git-novice-es/

**Comment by olemis** [comment]
@raynamharris PR #68 created to fix this issue

**Comment by raynamharris** [comment]
Thanks!

**Comment by olemis** [comment]
@raynamharris I'm aware of the Carpentries-ES . I contributed with one or two translations over there . Is that org closed . How are we handling Spanish translations now . 

<ot> I ask because some of my translators will start working on@swcarpentry and @datacarpentry content. Priorities documented somewhere ? </ot>

**Comment by raynamharris** [comment]
These are great questions. 

There isn't a hard and fast rule and I'm not the lack of rules is documented. Data Carpentry has a history of building new lessons outside the official Data Carpentry GitHub and then importing them when finished. The Carpentries-Es GitHub served as a nice place for building the lesson while we figured out where the would live permanently. On the other hand, Software Carpentry has always built and maintained lessons in their main GitHub repo. 

Becuase the https://github.com/Carpentries-ES repo has a nice community and has `Convenciones_Traduccion.md`, I think this is a good place to translate new before migrating the near-final version to either Data Carpentry or Software Carpentry. 

The *only rule* that I'm aware of is that we use the *import repository* function rather than *forking repository* functionality before beginning translations. 

Does that make sense?

**Comment by olemis** [comment]
Ok , I just wanted to be know to explain the workflow to new translators .

Thanks

**Comment by raynamharris** [comment]
I opened a new issues @olemis . Thanks for starting an [ot]
